// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Pemilik struct {
	ID            int64          `json:"id"`
	Nama          string         `json:"nama"`
	Ktp           string         `json:"ktp"`
	Jabatan       sql.NullString `json:"jabatan"`
	Alamat        sql.NullString `json:"alamat"`
	Kecamatan     sql.NullString `json:"kecamatan"`
	Kelurahan     sql.NullString `json:"kelurahan"`
	KabupatenKota sql.NullString `json:"kabupaten_kota"`
	KodePos       sql.NullString `json:"kode_pos"`
	Telepon       sql.NullString `json:"telepon"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     sql.NullInt64  `json:"created_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UpdatedBy     sql.NullInt64  `json:"updated_by"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DeletedBy     sql.NullInt64  `json:"deleted_by"`
}

type Pengelola struct {
	ID            int64          `json:"id"`
	Nama          string         `json:"nama"`
	Ktp           string         `json:"ktp"`
	Jabatan       sql.NullString `json:"jabatan"`
	Alamat        sql.NullString `json:"alamat"`
	Kecamatan     sql.NullString `json:"kecamatan"`
	Kelurahan     sql.NullString `json:"kelurahan"`
	KabupatenKota sql.NullString `json:"kabupaten_kota"`
	KodePos       sql.NullString `json:"kode_pos"`
	Telepon       sql.NullString `json:"telepon"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     sql.NullInt64  `json:"created_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UpdatedBy     sql.NullInt64  `json:"updated_by"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DeletedBy     sql.NullInt64  `json:"deleted_by"`
}

type Role struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   sql.NullInt64  `json:"created_by"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UpdatedBy   sql.NullInt64  `json:"updated_by"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	DeletedBy   sql.NullInt64  `json:"deleted_by"`
}

type User struct {
	ID             int64         `json:"id"`
	Username       string        `json:"username"`
	Name           string        `json:"name"`
	HashedPassword string        `json:"hashed_password"`
	RoleID         sql.NullInt64 `json:"role_id"`
	CreatedAt      time.Time     `json:"created_at"`
	CreatedBy      sql.NullInt64 `json:"created_by"`
	UpdatedAt      time.Time     `json:"updated_at"`
	UpdatedBy      sql.NullInt64 `json:"updated_by"`
	DeletedAt      sql.NullTime  `json:"deleted_at"`
	DeletedBy      sql.NullInt64 `json:"deleted_by"`
}

type WajibPajak struct {
	ID            int64          `json:"id"`
	Npwpd         string         `json:"npwpd"`
	Golongan      sql.NullString `json:"golongan"`
	NoPendaftaran sql.NullString `json:"no_pendaftaran"`
	TanggalDaftar time.Time      `json:"tanggal_daftar"`
	NamaJalan     sql.NullString `json:"nama_jalan"`
	Nomor         sql.NullString `json:"nomor"`
	Rt            sql.NullString `json:"rt"`
	Rw            sql.NullString `json:"rw"`
	Kecamatan     sql.NullString `json:"kecamatan"`
	Kelurahan     sql.NullString `json:"kelurahan"`
	KabupatenKota sql.NullString `json:"kabupaten_kota"`
	KodePos       sql.NullString `json:"kode_pos"`
	Telepon       sql.NullString `json:"telepon"`
	Email         sql.NullString `json:"email"`
	PemilikID     sql.NullInt64  `json:"pemilik_id"`
	PengelolaID   sql.NullInt64  `json:"pengelola_id"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     sql.NullInt64  `json:"created_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UpdatedBy     sql.NullInt64  `json:"updated_by"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DeletedBy     sql.NullInt64  `json:"deleted_by"`
}
