// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: wajib_pajak.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWajibPajak = `-- name: CreateWajibPajak :one
INSERT INTO wajib_pajak (
    npwpd,
    golongan,
    no_pendaftaran,
    tanggal_daftar,
    nama_jalan,
    nomor,
    rt,
    rw,
    kecamatan,
    kelurahan,
    kabupaten_kota,
    kode_pos,
    telepon,
    email,
    pemilik_id,
    pengelola_id,
    created_by,
    updated_by
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
             $11, $12, $13, $14, $15, $16, $17, $18
         ) RETURNING id, npwpd, golongan, no_pendaftaran, tanggal_daftar, nama_jalan, nomor, rt, rw, kecamatan, kelurahan, kabupaten_kota, kode_pos, telepon, email, pemilik_id, pengelola_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateWajibPajakParams struct {
	Npwpd         string         `json:"npwpd"`
	Golongan      sql.NullString `json:"golongan"`
	NoPendaftaran sql.NullString `json:"no_pendaftaran"`
	TanggalDaftar time.Time      `json:"tanggal_daftar"`
	NamaJalan     sql.NullString `json:"nama_jalan"`
	Nomor         sql.NullString `json:"nomor"`
	Rt            sql.NullString `json:"rt"`
	Rw            sql.NullString `json:"rw"`
	Kecamatan     sql.NullString `json:"kecamatan"`
	Kelurahan     sql.NullString `json:"kelurahan"`
	KabupatenKota sql.NullString `json:"kabupaten_kota"`
	KodePos       sql.NullString `json:"kode_pos"`
	Telepon       sql.NullString `json:"telepon"`
	Email         sql.NullString `json:"email"`
	PemilikID     sql.NullInt64  `json:"pemilik_id"`
	PengelolaID   sql.NullInt64  `json:"pengelola_id"`
	CreatedBy     sql.NullInt64  `json:"created_by"`
	UpdatedBy     sql.NullInt64  `json:"updated_by"`
}

func (q *Queries) CreateWajibPajak(ctx context.Context, arg CreateWajibPajakParams) (WajibPajak, error) {
	row := q.db.QueryRowContext(ctx, createWajibPajak,
		arg.Npwpd,
		arg.Golongan,
		arg.NoPendaftaran,
		arg.TanggalDaftar,
		arg.NamaJalan,
		arg.Nomor,
		arg.Rt,
		arg.Rw,
		arg.Kecamatan,
		arg.Kelurahan,
		arg.KabupatenKota,
		arg.KodePos,
		arg.Telepon,
		arg.Email,
		arg.PemilikID,
		arg.PengelolaID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i WajibPajak
	err := row.Scan(
		&i.ID,
		&i.Npwpd,
		&i.Golongan,
		&i.NoPendaftaran,
		&i.TanggalDaftar,
		&i.NamaJalan,
		&i.Nomor,
		&i.Rt,
		&i.Rw,
		&i.Kecamatan,
		&i.Kelurahan,
		&i.KabupatenKota,
		&i.KodePos,
		&i.Telepon,
		&i.Email,
		&i.PemilikID,
		&i.PengelolaID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getWajibPajakDetail = `-- name: GetWajibPajakDetail :one
SELECT
    wp.id AS wajib_pajak_id,
    wp.npwpd,
    wp.golongan,
    wp.no_pendaftaran,
    wp.tanggal_daftar,
    wp.nama_jalan,
    wp.nomor,
    wp.rt,
    wp.rw,
    wp.kecamatan AS wp_kecamatan,
    wp.kelurahan AS wp_kelurahan,
    wp.kabupaten_kota AS wp_kabupaten_kota,
    wp.kode_pos AS wp_kode_pos,
    wp.telepon AS wp_telepon,
    wp.email AS wp_email,

    -- Data Pemilik
    p.id AS pemilik_id,
    p.nama AS pemilik_nama,
    p.ktp AS pemilik_ktp,
    p.jabatan AS pemilik_jabatan,
    p.alamat AS pemilik_alamat,
    p.kecamatan AS pemilik_kecamatan,
    p.kelurahan AS pemilik_kelurahan,
    p.kabupaten_kota AS pemilik_kabupaten_kota,
    p.kode_pos AS pemilik_kode_pos,
    p.telepon AS pemilik_telepon,

    -- Data Pengelola
    pg.id AS pengelola_id,
    pg.nama AS pengelola_nama,
    pg.ktp AS pengelola_ktp,
    pg.jabatan AS pengelola_jabatan,
    pg.alamat AS pengelola_alamat,
    pg.kecamatan AS pengelola_kecamatan,
    pg.kelurahan AS pengelola_kelurahan,
    pg.kabupaten_kota AS pengelola_kabupaten_kota,
    pg.kode_pos AS pengelola_kode_pos,
    pg.telepon AS pengelola_telepon

FROM wajib_pajak wp
         LEFT JOIN pemilik p ON wp.pemilik_id = p.id
         LEFT JOIN pengelola pg ON wp.pengelola_id = pg.id
WHERE wp.id = $1
`

type GetWajibPajakDetailRow struct {
	WajibPajakID           int64          `json:"wajib_pajak_id"`
	Npwpd                  string         `json:"npwpd"`
	Golongan               sql.NullString `json:"golongan"`
	NoPendaftaran          sql.NullString `json:"no_pendaftaran"`
	TanggalDaftar          time.Time      `json:"tanggal_daftar"`
	NamaJalan              sql.NullString `json:"nama_jalan"`
	Nomor                  sql.NullString `json:"nomor"`
	Rt                     sql.NullString `json:"rt"`
	Rw                     sql.NullString `json:"rw"`
	WpKecamatan            sql.NullString `json:"wp_kecamatan"`
	WpKelurahan            sql.NullString `json:"wp_kelurahan"`
	WpKabupatenKota        sql.NullString `json:"wp_kabupaten_kota"`
	WpKodePos              sql.NullString `json:"wp_kode_pos"`
	WpTelepon              sql.NullString `json:"wp_telepon"`
	WpEmail                sql.NullString `json:"wp_email"`
	PemilikID              sql.NullInt64  `json:"pemilik_id"`
	PemilikNama            sql.NullString `json:"pemilik_nama"`
	PemilikKtp             sql.NullString `json:"pemilik_ktp"`
	PemilikJabatan         sql.NullString `json:"pemilik_jabatan"`
	PemilikAlamat          sql.NullString `json:"pemilik_alamat"`
	PemilikKecamatan       sql.NullString `json:"pemilik_kecamatan"`
	PemilikKelurahan       sql.NullString `json:"pemilik_kelurahan"`
	PemilikKabupatenKota   sql.NullString `json:"pemilik_kabupaten_kota"`
	PemilikKodePos         sql.NullString `json:"pemilik_kode_pos"`
	PemilikTelepon         sql.NullString `json:"pemilik_telepon"`
	PengelolaID            sql.NullInt64  `json:"pengelola_id"`
	PengelolaNama          sql.NullString `json:"pengelola_nama"`
	PengelolaKtp           sql.NullString `json:"pengelola_ktp"`
	PengelolaJabatan       sql.NullString `json:"pengelola_jabatan"`
	PengelolaAlamat        sql.NullString `json:"pengelola_alamat"`
	PengelolaKecamatan     sql.NullString `json:"pengelola_kecamatan"`
	PengelolaKelurahan     sql.NullString `json:"pengelola_kelurahan"`
	PengelolaKabupatenKota sql.NullString `json:"pengelola_kabupaten_kota"`
	PengelolaKodePos       sql.NullString `json:"pengelola_kode_pos"`
	PengelolaTelepon       sql.NullString `json:"pengelola_telepon"`
}

func (q *Queries) GetWajibPajakDetail(ctx context.Context, id int64) (GetWajibPajakDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getWajibPajakDetail, id)
	var i GetWajibPajakDetailRow
	err := row.Scan(
		&i.WajibPajakID,
		&i.Npwpd,
		&i.Golongan,
		&i.NoPendaftaran,
		&i.TanggalDaftar,
		&i.NamaJalan,
		&i.Nomor,
		&i.Rt,
		&i.Rw,
		&i.WpKecamatan,
		&i.WpKelurahan,
		&i.WpKabupatenKota,
		&i.WpKodePos,
		&i.WpTelepon,
		&i.WpEmail,
		&i.PemilikID,
		&i.PemilikNama,
		&i.PemilikKtp,
		&i.PemilikJabatan,
		&i.PemilikAlamat,
		&i.PemilikKecamatan,
		&i.PemilikKelurahan,
		&i.PemilikKabupatenKota,
		&i.PemilikKodePos,
		&i.PemilikTelepon,
		&i.PengelolaID,
		&i.PengelolaNama,
		&i.PengelolaKtp,
		&i.PengelolaJabatan,
		&i.PengelolaAlamat,
		&i.PengelolaKecamatan,
		&i.PengelolaKelurahan,
		&i.PengelolaKabupatenKota,
		&i.PengelolaKodePos,
		&i.PengelolaTelepon,
	)
	return i, err
}
